"""
Page Object 自動產生器：從 HTML 抽 ``data-testid`` / ``id`` / form fields，
render 出 Python 的 POM 模組。
Page Object Model code generator. Walks an HTML snapshot, picks every
element worth wrapping (in priority order: ``data-testid`` → ``id`` →
input ``name``), and renders a ``WebRunnerPage`` Python class with one
property per element returning a ``TestObject``.

The HTML parser is the standard-library :mod:`html.parser` so no extra
dependency is required.
"""
from __future__ import annotations

import keyword
import re
from dataclasses import dataclass
from html.parser import HTMLParser
from typing import Any, Dict, List, Sequence

from je_web_runner.utils.exception.exceptions import WebRunnerException


class PomCodegenError(WebRunnerException):
    """Raised on invalid input or duplicate-key conflicts."""


@dataclass
class DiscoveredElement:
    name: str           # python identifier
    strategy: str       # ID / NAME / CSS_SELECTOR / data-testid
    value: str          # locator value
    tag: str
    source: str         # data-testid / id / name


_PY_IDENT_SAFE = re.compile(r"\W+")


def _to_identifier(text: str, fallback: str) -> str:
    if not text:
        return fallback
    cleaned = _PY_IDENT_SAFE.sub("_", text.strip()).strip("_").lower()
    if not cleaned:
        return fallback
    if cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    if keyword.iskeyword(cleaned):
        cleaned = f"{cleaned}_"
    return cleaned


_PRIORITY_KEYS = ("data-testid", "id", "name")


class _ElementCollector(HTMLParser):

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.elements: List[DiscoveredElement] = []
        self._used_names: Dict[str, int] = {}

    def handle_starttag(self, tag: str, attrs: List[Any]) -> None:
        attr_dict = {name: value for name, value in attrs if isinstance(name, str)}
        for source in _PRIORITY_KEYS:
            value = attr_dict.get(source)
            if not isinstance(value, str) or not value:
                continue
            self._record(tag=tag, source=source, value=value)
            return

    def _record(self, tag: str, source: str, value: str) -> None:
        base_name = _to_identifier(value, fallback=tag.lower())
        # Deduplicate identifiers so two elements with the same data-testid
        # land as ``primary`` and ``primary_2``.
        count = self._used_names.get(base_name, 0)
        identifier = base_name if count == 0 else f"{base_name}_{count + 1}"
        self._used_names[base_name] = count + 1
        if source == "id":
            strategy, locator_value = "ID", value
        elif source == "name":
            strategy, locator_value = "NAME", value
        else:
            strategy, locator_value = "CSS_SELECTOR", f'[data-testid="{value}"]'
        self.elements.append(DiscoveredElement(
            name=identifier,
            strategy=strategy,
            value=locator_value,
            tag=tag,
            source=source,
        ))


def discover_elements_from_html(html: str) -> List[DiscoveredElement]:
    """Collect every wrap-worthy element from the HTML snapshot."""
    if not isinstance(html, str):
        raise PomCodegenError("html must be str")
    parser = _ElementCollector()
    parser.feed(html)
    parser.close()
    return parser.elements


_HEADER = '''\
"""Auto-generated Page Object module — do NOT edit by hand.

Generated by :func:`je_web_runner.utils.pom_codegen.codegen.render_pom_module`.
Each property returns a fresh ``TestObject`` so callers stay free to chain
finders without sharing state.
"""
from __future__ import annotations

from je_web_runner import TestObject


class {class_name}:
    """Page object for the source page."""
'''


def render_pom_module(
    elements: Sequence[DiscoveredElement],
    class_name: str = "WebRunnerPage",
) -> str:
    """Render a Python module string defining ``class_name``."""
    if not isinstance(class_name, str) or not class_name.isidentifier():
        raise PomCodegenError(f"class_name must be a valid identifier: {class_name!r}")
    if not elements:
        return _HEADER.format(class_name=class_name) + "\n    pass\n"
    lines = [_HEADER.format(class_name=class_name), ""]
    for element in elements:
        value_literal = element.value.replace("\\", "\\\\").replace('"', '\\"')
        comment = f"<{element.tag}> via {element.source}"
        lines.append("    @property")
        lines.append(f"    def {element.name}(self) -> TestObject:")
        lines.append(f'        """{comment}."""')
        lines.append(
            f'        return TestObject("{value_literal}", "{element.strategy}")'
        )
        lines.append("")
    return "\n".join(lines)
