from je_web_runner import execute_action

test_execute_list = [
    ["WR_get_webdriver_manager", {"webdriver_name": "firefox", "options": ["--headless"]}],
    ["WR_add_package_to_executor", {"package": "time"}],
    ["WR_implicitly_wait", {"time_to_wait": 5}],
    ["WR_to_url", {"url": "https://www.google.com"}],
    ["time_sleep", [3]],
    ["WR_SaveTestObject", {"test_object_name": "q", "object_type": "name"}],
    ["WR_find_element", {"element_name": "q"}],
    ["WR_click_element"],
    ["WR_input_to_element", {"input_value": "test 123 test do you read"}],
    ["WR_to_url", {"url": "https://www.google.com"}],
    ["WR_move_to_element", {"element_name": "q"}],
    ["WR_move_to_element_with_offset", {"element_name": "q", "offset_x": 10, "offset_y": 10}],
    ["WR_move_by_offset", {"offset_x": 10, "offset_y": 10}],
    ["WR_drag_and_drop", {"element_name": "q", "target_element_name": "q"}],
    ["WR_drag_and_drop_offset", {"element_name": "q", "offset_x": 10, "offset_y": 10}],
    ["WR_perform"],
    ["WR_left_click", {"element_name": "q"}],
    ["WR_release", {"element_name": "q"}],
    ["WR_left_click"],
    ["WR_release"],
    ["WR_left_double_click"],
    ["WR_release"],
    ["WR_left_double_click"],
    ["WR_left_click_and_hold"],
    ["WR_to_url", {"url": "https://www.google.com"}],
    ["time_sleep", [3]],
    ["WR_find_element", {"element_name": "q"}],
    ["WR_input_to_element", {"input_value": "test input1"}],
    ["time_sleep", [3]],
    ["WR_to_url", {"url": "https://www.google.com"}],
    ["time_sleep", [3]],
    ["WR_find_element", {"element_name": "q"}],
    ["WR_input_to_element", {"input_value": "test input again"}],
    ["time_sleep", [3]],
    ["WR_to_url", {"url": "https://www.google.com"}],
    ["time_sleep", [3]],
    ["WR_find_element", {"element_name": "q"}],
    ["WR_input_to_element", {"input_value": "12345678"}],
    ["time_sleep", [3]],
    ["WR_quit"]
]

execute_action(test_execute_list)
