"""
Workspace bootstrapper：``python -m je_web_runner --init`` 拉一份 starter。
Scaffold a starter WebRunner workspace with sample actions, ledger,
schema config, pre-commit hook, and a minimal GitHub Actions workflow so
new users can run their first test in under 10 minutes.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

from je_web_runner.utils.exception.exceptions import WebRunnerException


class BootstrapError(WebRunnerException):
    """Raised when the target directory is not safe to write into."""


@dataclass
class StarterFile:
    relative_path: str
    content: str


_SAMPLE_ACTIONS = [
    ["WR_new_driver", {"webdriver_name": "chrome"}],
    ["WR_to_url", {"url": "https://example.com"}],
    ["WR_save_test_object", {"test_object_name": "h1",
                             "object_type": "TAG_NAME"}],
    ["WR_find_recorded_element", {"element_name": "h1"}],
    ["WR_quit_all"],
]


_PRE_COMMIT_HOOK = """\
#!/bin/sh
# Generated by `python -m je_web_runner --init`. Lint action JSON before commit.
set -e
python -m je_web_runner --validate ./actions
"""


_GH_WORKFLOW = """\
name: WebRunner

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  webrunner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install je_web_runner
      - run: python -m je_web_runner --validate ./actions
"""


_README = """\
# WebRunner workspace

Scaffolded by `python -m je_web_runner --init`.

## Layout

- `actions/` — JSON action files run via `python -m je_web_runner -d ./actions`.
- `.webrunner/ledger.json` — runtime state (created on first run).
- `.webrunner/drivers.json` — pinned driver versions (optional).
- `.github/workflows/webrunner.yml` — CI gate.

## Try it

```bash
python -m je_web_runner -e ./actions/sample.json
python -m je_web_runner --validate ./actions
```
"""


_DRIVERS_PIN_TEMPLATE = {
    "drivers": []
}


_SCHEMA_HINT = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "array",
    "items": {
        "oneOf": [
            {"type": "array", "minItems": 1, "maxItems": 3},
        ]
    }
}


def starter_files() -> List[StarterFile]:
    """Return the full list of files written by :func:`init_workspace`."""
    return [
        StarterFile(
            relative_path="actions/sample.json",
            content=json.dumps(_SAMPLE_ACTIONS, ensure_ascii=False, indent=2) + "\n",
        ),
        StarterFile(relative_path=".webrunner/ledger.json",
                    content=json.dumps({"runs": []}, indent=2) + "\n"),
        StarterFile(
            relative_path=".webrunner/drivers.json",
            content=json.dumps(_DRIVERS_PIN_TEMPLATE, indent=2) + "\n",
        ),
        StarterFile(
            relative_path=".webrunner/action-schema.json",
            content=json.dumps(_SCHEMA_HINT, indent=2) + "\n",
        ),
        StarterFile(relative_path="README.md", content=_README),
        StarterFile(relative_path=".githooks/pre-commit", content=_PRE_COMMIT_HOOK),
        StarterFile(relative_path=".github/workflows/webrunner.yml",
                    content=_GH_WORKFLOW),
        StarterFile(relative_path=".gitignore",
                    content=".webrunner/cache/\nWEBRunner.log\n*.tmp\n"),
    ]


def init_workspace(
    directory: str,
    overwrite: bool = False,
    files_to_write: List[StarterFile] = None,
) -> Dict[str, str]:
    """
    建立 starter 結構。回傳 ``{relative_path: 'created' | 'skipped'}``。
    Write each starter file under ``directory``; existing files are skipped
    unless ``overwrite=True``.
    """
    base = Path(directory)
    if base.exists() and not base.is_dir():
        raise BootstrapError(f"target {directory!r} is not a directory")
    base.mkdir(parents=True, exist_ok=True)
    files = files_to_write if files_to_write is not None else starter_files()
    report: Dict[str, str] = {}
    for entry in files:
        target = base / entry.relative_path
        if target.exists() and not overwrite:
            report[entry.relative_path] = "skipped"
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(entry.content, encoding="utf-8")
        if entry.relative_path.startswith(".githooks/"):
            try:
                target.chmod(0o755)
            except OSError:
                pass
        report[entry.relative_path] = "created"
    return report
