from je_web_runner import webdriver_wrapper_instance, TestObject, Keys

webdriver_wrapper_instance.set_driver("firefox")
webdriver_wrapper_instance.to_url("https://google.com")
google_input = TestObject("q", "name")
google_input_element = webdriver_wrapper_instance.find_element(google_input)
webdriver_wrapper_instance.implicitly_wait(3)
webdriver_wrapper_instance.move_to_element(google_input_element)
webdriver_wrapper_instance.move_to_element_with_offset(google_input_element, 10, 10)
webdriver_wrapper_instance.move_by_offset(10, 10)
webdriver_wrapper_instance.drag_and_drop(google_input_element, google_input_element)
webdriver_wrapper_instance.drag_and_drop_offset(google_input_element, 10, 10)
webdriver_wrapper_instance.perform()
webdriver_wrapper_instance.left_click(google_input_element)
webdriver_wrapper_instance.release(google_input_element)
webdriver_wrapper_instance.left_click()
webdriver_wrapper_instance.release()
webdriver_wrapper_instance.left_double_click()
webdriver_wrapper_instance.release()
webdriver_wrapper_instance.left_click_and_hold()
webdriver_wrapper_instance.release()
webdriver_wrapper_instance.pause(3)
webdriver_wrapper_instance.press_key("H")
webdriver_wrapper_instance.release_key("H")
webdriver_wrapper_instance.send_keys("HE")
webdriver_wrapper_instance.send_keys_to_element(google_input_element, "LLO")
webdriver_wrapper_instance.perform()
webdriver_wrapper_instance.quit()
