"""Generate ``docs/reference/utils_index.md``: every ``je_web_runner/utils`` subpackage by theme.

Layers, in order: the core engine that every action runs through (``CORE``), then one section
per ``je_web_runner.api`` facade theme holding the subpackages that theme re-exports (the theme
module's first docstring line is the heading), then every other feature subpackage. Each
subpackage is listed once. A row's summary is the first docstring line of the subpackage's
``__init__.py``, else the package's text in ``CORE``, else the first docstring line of its first
documented module.

Usage: ``python scripts/gen_utils_index.py`` rewrites the file; ``--check`` exits 1 when the
committed file differs from what would be generated (``test/unit_test/test_utils_index.py``
runs the same comparison).
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
UTILS_DIR = REPO_ROOT / "je_web_runner" / "utils"
API_DIR = REPO_ROOT / "je_web_runner" / "api"
INDEX_PATH = REPO_ROOT / "docs" / "reference" / "utils_index.md"
UTILS_PREFIX = "je_web_runner.utils."
OTHER_THEME = "Other feature subpackages"
NO_SUMMARY = "(no docstring)"
# The engine layer (see CLAUDE.md "Architecture"), with a summary for packages that have no docstring.
CORE = {
    "assert_value": "Result checks behind the assertion actions.",
    "callback": "Callback executor: run a WR_* command, then a user callback (Observer).",
    "exception": "WebRunner exception hierarchy and error-message tags.",
    "executor": "Action executor: resolves WR_* command names and runs action lists (Command).",
    "file_process": "Directory listing used by the batch runners.",
    "generate_report": "Report generators: HTML, JSON, XML, JUnit XML and Allure (Strategy).",
    "json": "Action JSON file read and write, and structure validation before a run.",
    "logging": "Rotating file logger for WebRunner.",
    "package_manager": "Loads a package at run time and registers its members as commands (Plugin).",
    "project": "Project template generator for a new WebRunner workspace.",
    "selenium_utils_wrapper": "Selenium key and desired-capability tables.",
    "socket_server": "TCP socket server that runs action JSON sent by remote clients.",
    "test_object": "Test objects: locator name and strategy pairs (Value Object).",
    "test_record": "Records executed actions for the reports.",
    "xml": "XML file read and write, and XML <-> dict conversion.",
}


def _first_line(docstring: str | None) -> str | None:
    if not docstring:
        return None
    for line in docstring.strip().splitlines():
        if line.strip():
            return line.strip()
    return None


def _module_docstring(path: Path) -> str | None:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError, UnicodeDecodeError):
        return None
    return ast.get_docstring(tree)


def subpackage_summary(package: Path) -> str:
    """One-line summary of a subpackage.

    Its ``__init__`` docstring, else its ``CORE`` text, else its first documented module. A core
    package's ``CORE`` text beats a module docstring, which would describe only that module.
    """
    line = _first_line(_module_docstring(package / "__init__.py")) or CORE.get(package.name)
    if not line:
        modules = sorted(p for p in package.glob("*.py") if p.name != "__init__.py")
        line = next(filter(None, (_first_line(_module_docstring(p)) for p in modules)), None)
    return line.replace("|", "\\|") if line else NO_SUMMARY


def subpackages() -> list[str]:
    """Names of the subpackages directly under ``je_web_runner/utils``."""
    return sorted(
        p.name for p in UTILS_DIR.iterdir()
        if p.is_dir() and (p / "__init__.py").exists()
    )


def facade_themes() -> dict[str, tuple[str, set[str]]]:
    """Map each ``api`` theme module to ``(heading, utils subpackages it re-exports)``."""
    themes = {}
    for path in sorted(API_DIR.glob("*.py")):
        if path.name == "__init__.py":
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"))
        heading = _first_line(ast.get_docstring(tree)) or path.stem
        packages = {
            node.module[len(UTILS_PREFIX):].split(".")[0]
            for node in ast.walk(tree)
            if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith(UTILS_PREFIX)
        }
        themes[path.stem] = (heading, packages)
    return themes


def render() -> str:
    """The full Markdown text of the index."""
    names = subpackages()
    themes = facade_themes()
    core = [n for n in names if n in CORE]
    placed: set[str] = set(core)
    lines = [
        "# `je_web_runner/utils` index",
        "",
        "Generated by `scripts/gen_utils_index.py`; do not edit by hand.",
        f"{len(names)} subpackages: the core engine, then one section per `je_web_runner.api` facade theme,",
        "then the other feature subpackages.",
        "",
    ]
    lines += _section("Core engine", core)
    sections = [(stem, heading, sorted(pkgs & set(names))) for stem, (heading, pkgs) in themes.items()]
    for stem, heading, members in sections:
        members = [m for m in members if m not in placed]
        if not members:
            continue
        placed.update(members)
        lines += _section(f"`api.{stem}` — {heading}", members)
    rest = [n for n in names if n not in placed]
    if rest:
        lines += _section(OTHER_THEME, rest)
    return "\n".join(lines).rstrip("\n") + "\n"


def _section(title: str, members: list[str]) -> list[str]:
    rows = [f"## {title}", "", "| Subpackage | Summary |", "|---|---|"]
    rows += [f"| `{name}` | {subpackage_summary(UTILS_DIR / name)} |" for name in members]
    return rows + [""]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the committed index is stale")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if current != text:
            print(f"{INDEX_PATH.relative_to(REPO_ROOT)} is stale; run python scripts/gen_utils_index.py")
            return 1
        return 0
    INDEX_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
