from je_web_runner import webdriver_wrapper_instance

webdriver_wrapper_instance.set_driver("firefox")
webdriver_wrapper_instance.implicitly_wait(5)
webdriver_wrapper_instance.set_page_load_timeout(5)
webdriver_wrapper_instance.set_script_timeout(5)
webdriver_wrapper_instance.quit()
